---
- name: Playbook instalare Docker
  hosts: localhost
  become: true
  vars:
    docker_compose_version: 1.29.2
  tasks:
  - name: Eliminare pachete incompatibile
    apt:
      name:
      - docker-engine
      - docker.io
      - containerd
      - runc
      state: absent

  - name: Instalare prerechizite
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      state: present

  - name: Adaugare cheie semnare repository Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Instalare sursa depozit apt pentru Docker
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present

  - name: Instalare Docker
    apt:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: present
      update_cache: yes
      cache_valid_time: 3600

  - name: Instalare module python pentru Docker
    pip:
      name: docker

  - name: Instalare docker-compose
    get_url:
      url : https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'
